export const PATHS = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  dashboard: '/dashboard',
  profile: '/profile',
  adminUsers: '/admin/users',
  adminSports: '/admin/sports',
  adminFacilities: '/admin/facilities',
  adminSettings: '/admin/settings',
  adminAuditLogs: '/admin/audit-logs',
  receptionMembers: '/reception/members',
  notifications: '/notifications',
} as const;
