import type { AuditEntityType } from '@sports-center/shared';

import type {
  Account,
  BankTransaction,
  Class,
  ClassCoachRegistration,
  ClassSession,
  CoachProfile,
  CoachSpecialization,
  Coupon,
  Course,
  Facility,
  FacilityMaintenance,
  ManagerProfile,
  MemberMembership,
  MemberProfile,
  Membership,
  ReceptionistProfile,
  Sport,
  SystemSetting,
  WalletTopUp,
} from '~/generated/prisma/client';

const fields =
  <T>() =>
  <K extends keyof T & string>(...keys: K[]): readonly string[] =>
    keys;

export const AUDIT_FIELDS: Record<AuditEntityType, readonly string[]> = {
  ACCOUNT: fields<Account>()(
    'email',
    'phone',
    'fullName',
    'avatarUrl',
    'role',
    'status',
    'emailVerifiedAt',
    'dateOfBirth',
    'gender',
    'address',
  ),
  MEMBER_PROFILE: fields<MemberProfile>()('emergencyContact', 'fitnessGoals'),
  COACH_PROFILE: fields<CoachProfile>()('bio', 'experience', 'certifications', 'coverImageUrl'),
  RECEPTIONIST_PROFILE: fields<ReceptionistProfile>()('staffNotes'),
  MANAGER_PROFILE: fields<ManagerProfile>()('staffNotes'),
  SPORT: fields<Sport>()('name', 'description', 'iconUrl', 'isActive', 'deletedAt'),
  FACILITY: fields<Facility>()(
    'name',
    'type',
    'capacityPerSlot',
    'pricePerSlot',
    'isActive',
    'description',
    'deletedAt',
  ),
  FACILITY_MAINTENANCE: fields<FacilityMaintenance>()('facilityId', 'startAt', 'endAt', 'reason', 'deletedAt'),
  COURSE: fields<Course>()('name', 'sportId', 'description', 'totalSessions', 'price', 'thumbnailUrl', 'deletedAt'),
  CLASS: fields<Class>()(
    'courseId',
    'coachId',
    'facilityId',
    'name',
    'minStudents',
    'minStudentsOverride',
    'maxStudents',
    'startDate',
    'endDate',
    'weeklySchedule',
    'status',
    'cancelReason',
    'deletedAt',
  ),
  CLASS_SESSION: fields<ClassSession>()('facilityId', 'sessionDate', 'startTime', 'endTime', 'status', 'cancelReason'),
  CLASS_COACH_REGISTRATION: fields<ClassCoachRegistration>()('classId', 'coachId', 'source', 'status'),
  COACH_SPECIALIZATION: fields<CoachSpecialization>()('coachId', 'sportId', 'status', 'reviewNote'),
  MEMBERSHIP: fields<Membership>()(
    'name',
    'description',
    'price',
    'durationDays',
    'gymAccess',
    'bookingDiscountPct',
    'classDiscountPct',
    'freeBookingSlotsPerMonth',
    'isActive',
    'deletedAt',
  ),
  MEMBER_MEMBERSHIP: fields<MemberMembership>()('packageId', 'startDate', 'endDate', 'autoRenew', 'status'),
  COUPON: fields<Coupon>()(
    'code',
    'name',
    'discountType',
    'discountValue',
    'maxDiscount',
    'minOrderAmount',
    'maxUses',
    'maxUsesPerUser',
    'applicableTypes',
    'validFrom',
    'validTo',
    'isActive',
    'deletedAt',
  ),
  SYSTEM_SETTING: fields<SystemSetting>()(
    'openTime',
    'closeTime',
    'slotDurationMinutes',
    'maxAdvanceBookingDays',
    'bookingCancelDeadlineHours',
    'courseCancelDeadlineDays',
    'membershipExpiryWarningDays',
    'topUpMinAmount',
    'topUpExpiryMinutes',
  ),
  BANK_TRANSACTION: fields<BankTransaction>()('amount', 'paymentCode', 'status', 'resolvedAccountId', 'note'),
  WALLET_TOP_UP: fields<WalletTopUp>()('accountId', 'amount', 'status', 'bankTransactionId'),
};
